version: '3.4'

services:
  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ytsemfake
      MONGO_INITDB_DATABASE: altcensoredscrapperdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /tmp/log/mongo
    ports:
      - "27017:27017"
    volumes:
      - ./src/data/db:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge

 
 